const mongoose = require("mongoose")
const User = require("./User")
// const Image = require('./Image');
const Schema = mongoose.Schema

/*
Columns -> brandname,title, description,bulletpoints,height,width,length,weight,mainimage, 
additionalimage1,additionalimage2,additionalimage3,additionalimage4,additionalimage5,
createdBy,price, quantity,
ratings[{useremail,username,rating:Number,title, description,createdAt,updatedAt}],
 questionsandanswer[{useremail,username,question,answer,createdAt,updatedAt}],
 createdAt,updatedAt.

*/

const ProductsSchema = new Schema({
    brandName:{
        type:String,
        default:null
    },
    title:{
        type:String,
        default:null
    },
    description:{
        type:String,
        default:null
    },
    bulletPoints:{
        type:String,
        default:null
    },
    height:{
        type:Number,
        defaule:0
    },
    width:{
        type:Number,
        default:0
    },
    length:{
        type:Number,
        default:0
    },
    weight:{
        type:Number,
        default:0
    },
    mainImage:{
        type:String,
        default:null
    },
    additionalImage1:{
        type:String,
        default:null
    },
    additionalImage2:{
        type:String,
        default:null
    },
    additionalImage3:{
        type:String,
        default:null
    },
    additionalImage4:{
        type:String,
        default:null
    },
    additionalImage5:{
        type:String,
        default:null
    },
    createdBy:{
        type:String,
        default:null
    },
    price:{
        type:Number,
        default:0
    },
    quantity:{
        type:Number,
        default:0
    },
    ratings:[{
        userEmail:{
            type:String,
            default:null
        },
        userName:{
            type:String,
            default:null
        },
        rating:{
            type:Number,
            default:0
        },
        title:{
            type:Number,
            default:0
        },
        description:{
            type:String,
            default:null
        },
        createdAt:{
            type:Date
        },
        updatedAt:{
            type:Date
        }
    }],
    questionsAndAnswers:[{
        userEmail:{
            type:String,
            default:null
        },
        userName:{
            type:String,
            default:null
        },
        question:{
            type:String,
            default:null
        },
        answer:{
            type:String,
            default:null
        },
        createdAt:{
            type:Date
        },
        updatedAt:{
            type:Date
        }
    }],
    createdAt:{
        type:Date
    },
    updatedAt:{
        type:Date
    }
},{timestamps:true})

module.exports = Products = mongoose.model("Products",ProductsSchema);